/*******************************************************************************
 * Copyright (c) 2009 MATERNA Information & Communications. All rights reserved.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html. For further
 * project-related information visit http://www.ws4d.org. The most recent
 * version of the JMEDS framework can be obtained from
 * http://sourceforge.net/projects/ws4d-javame.
 ******************************************************************************/
package org.ws4d.java.communication.protocol.soap.generator;

import java.io.IOException;
import java.io.OutputStream;

import org.ws4d.java.communication.connection.ip.IPConnectionInfo;
import org.ws4d.java.message.DiscoveryProxyProbeMatchesException;
import org.ws4d.java.message.Message;
import org.ws4d.java.types.AttributedURI;
import org.ws4d.java.types.ByteArrayBuffer;
import org.ws4d.java.util.WS4DIllegalStateException;

public interface Message2SOAPGenerator {

	/**
	 * Serialize an DPWS Message Object to the given output stream.
	 * 
	 * @param out stream, to which the element should be serialized.
	 * @param connectionInfo
	 * @param msg, which is use to get the Information
	 */
	public void generateSOAPMessage(OutputStream out, Message msg, IPConnectionInfo connectionInfo, AttributedURI optionalMessageId) throws IllegalArgumentException, WS4DIllegalStateException, IOException, DiscoveryProxyProbeMatchesException;

	/**
	 * Serialize an DPWS Message Object to an array of bytes.
	 * <P>
	 * <B>ATTENTION:</B> When the message generated by this method is not needed anymore return it for reuse by calling <code>returnBuffer(ByteArrayBuffer buffer)</code>
	 * 
	 * @param msg the message which is use to get the Information
	 * @return the message-buffer containing the generated message
	 *         representation
	 */
	public ByteArrayBuffer generateSOAPMessage(Message msg, IPConnectionInfo connectionInfo, AttributedURI optionalMessageId, boolean includeXAddrsInUDPHello) throws IOException, DiscoveryProxyProbeMatchesException;

	/**
	 * Return the current buffer of this instance to the cache for reuse
	 * 
	 * @param buffer the message-buffer returned by the latest invocation of <code>generateSOAPMessage(Message msg, ConnectionInfo ci)</code>
	 */
	public void returnCurrentBufferToCache();

	/**
	 * Return the current buffer of this instance
	 * 
	 * @return the message-buffer returned by the latest invocation of <code>generateSOAPMessage(Message msg, ConnectionInfo ci)</code>
	 */

	public ByteArrayBuffer getCurrentBuffer();
}